package sci.persistencia;
// Generated 02-sep-2018 16:06:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FacturaEncabezado generated by hbm2java
 */
public class FacturaEncabezado  implements java.io.Serializable {


     private Integer idFacturaEncabezado;
     private Contactos contactos;
     private Empresa empresa;
     private String fechaFactura;
     private String estado;
     private Set facturaDetalles = new HashSet(0);

    public FacturaEncabezado() {
    }

	
    public FacturaEncabezado(Contactos contactos, Empresa empresa) {
        this.contactos = contactos;
        this.empresa = empresa;
    }
    public FacturaEncabezado(Contactos contactos, Empresa empresa, String fechaFactura, String estado, Set facturaDetalles) {
       this.contactos = contactos;
       this.empresa = empresa;
       this.fechaFactura = fechaFactura;
       this.estado = estado;
       this.facturaDetalles = facturaDetalles;
    }
   
    public Integer getIdFacturaEncabezado() {
        return this.idFacturaEncabezado;
    }
    
    public void setIdFacturaEncabezado(Integer idFacturaEncabezado) {
        this.idFacturaEncabezado = idFacturaEncabezado;
    }
    public Contactos getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Contactos contactos) {
        this.contactos = contactos;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getFechaFactura() {
        return this.fechaFactura;
    }
    
    public void setFechaFactura(String fechaFactura) {
        this.fechaFactura = fechaFactura;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }




}


