package sci.persistencia;
// Generated 02-sep-2018 16:06:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Moneda generated by hbm2java
 */
public class Moneda  implements java.io.Serializable {


     private String nombreMoneda;
     private String simboloMoneda;
     private String codigoMoneda;
     private Double equivalencia;
     private String monedaReferencia;
     private Set configuracions = new HashSet(0);

    public Moneda() {
    }

	
    public Moneda(String nombreMoneda) {
        this.nombreMoneda = nombreMoneda;
    }
    public Moneda(String nombreMoneda, String simboloMoneda, String codigoMoneda, Double equivalencia, String monedaReferencia, Set configuracions) {
       this.nombreMoneda = nombreMoneda;
       this.simboloMoneda = simboloMoneda;
       this.codigoMoneda = codigoMoneda;
       this.equivalencia = equivalencia;
       this.monedaReferencia = monedaReferencia;
       this.configuracions = configuracions;
    }
   
    public String getNombreMoneda() {
        return this.nombreMoneda;
    }
    
    public void setNombreMoneda(String nombreMoneda) {
        this.nombreMoneda = nombreMoneda;
    }
    public String getSimboloMoneda() {
        return this.simboloMoneda;
    }
    
    public void setSimboloMoneda(String simboloMoneda) {
        this.simboloMoneda = simboloMoneda;
    }
    public String getCodigoMoneda() {
        return this.codigoMoneda;
    }
    
    public void setCodigoMoneda(String codigoMoneda) {
        this.codigoMoneda = codigoMoneda;
    }
    public Double getEquivalencia() {
        return this.equivalencia;
    }
    
    public void setEquivalencia(Double equivalencia) {
        this.equivalencia = equivalencia;
    }
    public String getMonedaReferencia() {
        return this.monedaReferencia;
    }
    
    public void setMonedaReferencia(String monedaReferencia) {
        this.monedaReferencia = monedaReferencia;
    }
    public Set getConfiguracions() {
        return this.configuracions;
    }
    
    public void setConfiguracions(Set configuracions) {
        this.configuracions = configuracions;
    }




}


